// Geographic reference values are distinct from the compressed, playable terrain.
export const BIOMES = [
  {
    id: 'rainforest',
    number: '01',
    name: 'Forêt tropicale humide',
    short: 'Forêt tropicale',
    region: 'EST',
    subtitle: 'Sous la canopée, un autre monde.',
    icon: 'leaf',
    color: '#58735a',
    image: 'rainforest',
    position: [48.65, -18.4],
    spawn: [145, -45],
    altitude: '0 – 1 500 m',
    temperature: '24°C',
    climate: 'Tropical humide',
    weather: 'Pluie & brume',
    soil: '#2B1E16',
    description:
      'Une forêt qui respire. La brume enveloppe les fougères géantes, les lianes et les cascades de la falaise orientale. Au loin, le chant des indris traverse la canopée.',
    features: ['Forêt primaire', 'Cascades', 'Lémuriens indri'],
    landmark: 'Parc national de Masoala',
    terrain: 'Escarpements & humus noir',
    rain: 0.8,
  },
  {
    id: 'highlands',
    number: '02',
    name: 'Hautes terres centrales',
    short: 'Hautes terres',
    region: 'CENTRE',
    subtitle: 'Le cœur rouge de Madagascar.',
    icon: 'mountain',
    color: '#b36344',
    image: 'highlands',
    position: [47.45, -19.15],
    spawn: [-26, 53],
    altitude: '800 – 1 500 m',
    temperature: '22°C',
    climate: 'Tropical d’altitude',
    weather: 'Éclaircies',
    soil: '#A0432A',
    description:
      'Des collines de latérite rouge, des rizières en miroir et des villages de briques. Ici, les terres sculptées par l’eau racontent l’âme de la grande île.',
    features: ['Rizières en terrasses', 'Lavaka', 'Villages de briques'],
    landmark: 'Antananarivo · les douze collines',
    terrain: 'Collines & plateaux granitiques',
    rain: 0.15,
  },
  {
    id: 'baobabs',
    number: '03',
    name: 'Savane & Tsingy',
    short: 'Savane & Tsingy',
    region: 'OUEST',
    subtitle: 'À l’ombre des géants.',
    icon: 'tree',
    color: '#aa8b49',
    image: 'baobabs',
    position: [44.8, -19.6],
    spawn: [-135, 35],
    altitude: '0 – 800 m',
    temperature: '32°C',
    climate: 'Tropical sec',
    weather: 'Soleil & poussière',
    soil: '#E6D5B8',
    description:
      'Les baobabs dressent leurs silhouettes au-dessus des herbes dorées. Plus au nord, les Tsingy forment une forêt de lames calcaires, un labyrinthe minéral à traverser avec précaution.',
    features: ['Baobabs grandidieri', 'Tsingy', 'Savane dorée'],
    landmark: 'Allée des Baobabs · Morondava',
    terrain: 'Plaines sédimentaires & calcaire',
    rain: 0.03,
  },
  {
    id: 'spiny',
    number: '04',
    name: 'Désert épineux',
    short: 'Désert épineux',
    region: 'SUD-OUEST',
    subtitle: 'La beauté d’une terre extrême.',
    icon: 'cactus',
    color: '#b3855a',
    image: 'spiny',
    position: [44.35, -24.1],
    spawn: [-55, 205],
    altitude: '0 – 600 m',
    temperature: '36°C',
    climate: 'Semi-aride',
    weather: 'Chaleur sèche',
    soil: '#BD7046',
    description:
      'Une autre planète au bout de l’île. Les didiéréacées et les euphorbes dessinent une forêt épineuse unique, enracinée dans un sable rouge brûlant.',
    features: ['Didiéréacées', 'Euphorbes', 'Sable rouge'],
    landmark: 'Forêt de Reniala · Ifaty',
    terrain: 'Sables arides & fourrés épineux',
    rain: 0.01,
  },
  {
    id: 'volcanic',
    number: '05',
    name: 'Terres volcaniques',
    short: 'Terres volcaniques',
    region: 'NORD',
    subtitle: 'Entre roche noire et émeraude.',
    icon: 'volcano',
    color: '#697462',
    image: 'volcanic',
    position: [49.1, -13.4],
    spawn: [-43, -183],
    altitude: '0 – 2 876 m',
    temperature: '25°C',
    climate: 'Tropical de montagne',
    weather: 'Brume d’altitude',
    soil: '#383830',
    description:
      'Des lacs de cratère, la forêt de la Montagne d’Ambre et la baie d’Antsiranana. Le Tsaratanana domine le nord : une roche sombre, sans manteau de neige permanent.',
    features: ['Lacs de cratère', 'Roche volcanique', 'Forêt de brume'],
    landmark: 'Maromokotro · 2 876 m',
    terrain: 'Massifs volcaniques & crêtes',
    rain: 0.55,
  },
  {
    id: 'coast',
    number: '06',
    name: 'Côtes & lagons',
    short: 'Côtes & lagons',
    region: 'LITTORAL & ÎLES',
    subtitle: 'L’île rencontre l’océan.',
    icon: 'waves',
    color: '#5d9890',
    image: 'coast',
    position: [48.25, -13.3],
    spawn: [-230, -100],
    altitude: '0 – 100 m',
    temperature: '29°C',
    climate: 'Tropical maritime',
    weather: 'Brise marine',
    soil: '#EEE3CA',
    description:
      'Des mangroves de l’ouest aux récifs de Nosy Be, le littoral change de visage. Sable blanc, eau turquoise et îlots contrastent avec les rivages exposés de l’est.',
    features: ['Récifs coralliens', 'Mangroves', 'Plages de Nosy Be'],
    landmark: 'Nosy Be · l’île aux parfums',
    terrain: 'Sable corallien & estuaires',
    rain: 0.2,
  },
  {
    id: 'rivers',
    number: '07',
    name: 'Rivières & Pangalanes',
    short: 'Rivières & canal',
    region: 'AU FIL DE L’EAU',
    subtitle: 'Les chemins vivants de l’île.',
    icon: 'river',
    color: '#698c87',
    image: 'rivers',
    position: [48.5, -20.5],
    spawn: [174, 90],
    altitude: '0 – 500 m',
    temperature: '27°C',
    climate: 'Tropical riverain',
    weather: 'Humidité & éclaircies',
    soil: '#93774C',
    description:
      'À l’est, les Pangalanes longent l’océan derrière un rideau de ravinalas. À l’ouest, la Tsiribihina et le Mangoky déploient leurs eaux ocre dans de larges vallées.',
    features: ['Ravinalas', 'Canal des Pangalanes', 'Eaux limoneuses'],
    landmark: 'Pangalanes · voie d’eau orientale',
    terrain: 'Canaux, berges & plaines alluviales',
    rain: 0.65,
  },
]
export const getBiome = (id) => BIOMES.find((biome) => biome.id === id) || BIOMES[1]

// Compressed game-space regions. Deliberately independent of atlas lat/lon.
export function biomeAt(x, z) {
  if (z < -150) return 'volcanic'
  if (x < -145 && z < -55) return 'coast'
  if (x > 165 && z > 25) return 'rivers'
  if (x > 95) return 'rainforest'
  if (z > 150 && x < 40) return 'spiny'
  if (x < -65) return 'baobabs'
  return 'highlands'
}
